### PR TITLE
cats 0.9.0

### PR DESCRIPTION
**Pull request by dvic**

### CODE REVIEW

**Comment by mandubian** [comment]
Thanks I think we need to upgrade minor version of freek too

**Comment by dvic** [comment]
Done 👍

**Comment by mandubian** [comment]
great ;)
I'll try to push that version on bintray soon!

**Comment by dborisenko** [comment]
Hi there! v0.6.7 doesn't seem to be available on bintray yet. I'm wondering, is it going to be there?

**Comment by mandubian** [comment]
you're right, I have simply forgotten to push it...
Let me push it!

**Comment by mandubian** [comment]
Can you check, it should be there... thks for reminding me!

**Comment by dborisenko** [comment]
@mandubian yes, it's there! Thanks!

**Pull request merged**
