### PR TITLE
Adding freekF method

### PR DESCRIPTION
**Pull request by zainab-ali**
Adding `freekF`, a method which lifts a `Free[F, A]`

### CODE REVIEW

**Comment by mandubian** [comment]
Thanks a lot @zainab-ali for this 1st PR 👍 

Could you check but I think existing function `.expand` does the same as yours:

https://github.com/ProjectSeptemberInc/freek/blob/master/src/main/scala/Freek.scala#L13-L19

and 

https://github.com/ProjectSeptemberInc/freek/blob/master/src/main/scala/package.scala#L30

**Comment by dwhitney** [comment]
perhaps freekF is a better name for expand? Hmm.... expand is more
explanitory, but freekF is maybe a little more familiar?

**Comment by mandubian** [comment]
The meaning is really to expand your `Free[DSL, A]` into a bigger DSL, `Free[BigDSL, A]`
`freekF` wouldn't bear this meaning from my point of view but I'm not so good at finding names as you know :D
WDYT?

**Comment by dwhitney** [comment]
yeah I agree with @mandubian

**Comment by zainab-ali** [comment]
There's a subtle difference between `expand` and `freekF`.

`expand` takes a `Free[DSL, A]` where `DSL` is a subtype of `CoproductK` and transforms it into a bigger dsl `Free[BigDSL, A]`

`freekF` takes a `Free[F, A]`, where `F` has no constraints, and transforms it into a `Free[DSL, A]`, and then transforms it into a `Free[BigDSL, A]`

I'm all for having a single method which tackles both cases, though I'm not sure how this could be done.

As for the name, I prefer `expand`, but didn't want naming conflicts.

**Comment by dwhitney** [comment]
ok, I see the difference, and yeah that seems like a better version of expand

**Comment by mandubian** [comment]
oh I see, you're right!
maybe we could create a new custom SubCop that works in both cases (F not CoproductK or CoproductK) to have one single function `expand`

**Comment by zainab-ali** [comment]
We could remove the `CoproductK` contstraint on `L` in  `SubCop[L[_] <: CoproductK[_], L2[_] <: CoproductK[_]]`, then write two implicits: one for a subtype of `CoproductK`, and one for something which isn't a subtype of `CoproductK`.

But I think that would complicate things far more than having two `expand` methods.  
Do you have an idea of what the custom `SubCop` would look like?

**Comment by mandubian** [comment]
I'll try to write it to see if it's reasonable or not...
I'm not against having several functions if it lessens the risk of crazy compile errors

**Comment by zainab-ali** [comment]
Any updates on this one?  If not, I'll resolve the conflicts.  IMO the current implementation is simpler than implicit manipulation.

**Comment by mandubian** [comment]
Could you try to synchronize with current master?
Things have moved a bit since this PR.
I have changed anything to SubCop yet as I was working on other ideas.
Thanks

**Comment by zainab-ali** [comment]
Synchronised

**Comment by zainab-ali** [comment]
Re-synchronised

**Comment by zainab-ali** [comment]
Re-synchronised

**Comment by mandubian** [comment]
Thanks dude!
I'm going to take that into account asap... busy lately ;)

**Pull request merged**
